repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0  # Update this with the desired version of Black
    hooks:
      - id: black
        language_version: python3.10.10  # Set the appropriate Python version
